### ISSUE TITLE
Running into srs longer than 256 characters

### ISSUE THREAD

**Issue by postfalk** [bkg/django-spillway#32]
Using 

```
gdalinfo 2003_01.01.250m_16_days_NDVI.tif
```

I am getting

```
PROJCS["SINUSOIDAL Unspecified Datum. Semi-major axis: 6371007.181000, Semi-minor axis: 0.000000",
    GEOGCS["unknown",
        DATUM["unknown",
            SPHEROID["unnamed",6371007.181,0]],
        PRIMEM["Greenwich",0],
        UNIT["degree",0.0174532925199433]],
    PROJECTION["Sinusoidal"],
    PARAMETER["longitude_of_center",0],
    PARAMETER["false_easting",0],
    PARAMETER["false_northing",0],
    UNIT["metre",1,
        AUTHORITY["EPSG","9001"]]]
```

... which has 395 characters with indention removed. The ```max_length``` attribute is hard to override because of the abstract model class. Do you have suggestions?

**Comment by bkg** [comment]
Ah, sorry about that, I should have considered the length more carefully. As you mentioned, there is not a straightfoward way to alter this in derived models.

The projcs name here is not standard and could be anything. You can run `gdalsrsinfo` on your projection to see the proj4 def is `+proj=sinu +lon_0=0 +x_0=0 +y_0=0 +a=6371007.181 +b=6371007.181 +units=m +no_defs`. Then run `gdalsrsinfo` on the resulting proj4 def. You can see the WKT representation contains `PROJCS["unnamed",` so you can use that. Ugh, nevermind, that is still 286 chars.

Instead of `CharField` with a max length, I think I will transition to `TextField` here.

**Comment by postfalk** [comment]
Ok, thank you very much.
Falk
________________________________
